# Contact information
agency: dems
year: 2017
title: dems
email: info@dems-agency.com
address: Jardi es de veracruz, del restaurante Tauro 2 cuadras abajo y 15 varas al oeste casa  I16
phone_movistar: tel:+50586889998
phone_claro: tel:+50586914848
website: http://www.dems-agency.com
facebook: https://www.facebook.com/demsagency
twitter: https://twitter.com/dems
instagram: https://www.instagram.com/dems
youtube: https://www.youtube.com/channel/UCqV-51GPkWR2mSMS_GcimsQ
linkedin: https://www.linkedin.com/company/dems

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dems-agency.com" # the base hostname & protocol for your site, e.g. http://example.com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
